### ISSUE TITLE
Why does decision tree dependes on DataFrame and Datasets?

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/decision-tree-model#6]
If you look at the baseline, it depends of dataFrame and Datasets. We should delete those dependencies

**Comment by jecisc** [comment]
Some part of the DecisionTree model seems to rely on the fact that the user gives a DataFrame.

For example: DtmDiscretizer>>#discretizableColumnsOf:

I'm not sure we really want that dependency, but if we want to remove it then we'll need to refactor the decision tree model before

**Comment by jordanmontt** [comment]
Yes agree, we need to refactor it to remove the dependency. After, we can add some extension methods in DataFrame if needed
